homeserverUrl: "https://t2bot.io"
accessToken: "YOUR_TOKEN_HERE"

# Settings for controlling how logging works
logging:
  file: logs/trellobot.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5